#!/bin/bash

# ECS Diagnostic Script
# This helps identify issues with your ECS deployment

CLUSTER="my-node-api-cluster"
SERVICE="node-app-service"
REGION="ap-southeast-2"

echo "📋 ECS Service Diagnostic Report"
echo "=================================="
echo ""
echo "Region: $REGION"
echo "Cluster: $CLUSTER"
echo "Service: $SERVICE"
echo ""

# Note: This script uses AWS CLI which may not be installed
# If AWS CLI is not available, follow manual steps below

echo "❌ Note: AWS CLI not available on your machine"
echo ""
echo "Please check these in AWS Console manually:"
echo ""
echo "=" 
echo "STEP 1: ECS Service Status"
echo "="
echo "1. Go to AWS Console → ECS"
echo "2. Click Clusters → my-node-api-cluster"
echo "3. Click Services → node-app-service"
echo "4. CHECK:"
echo "   - Status: ACTIVE"
echo "   - Desired Count: 1"
echo "   - Running Count: 1"
echo ""

echo "=" 
echo "STEP 2: Task Details"
echo "="
echo "1. Under Tasks tab, click the running task"
echo "2. CHECK:"
echo "   - Task Status: RUNNING"
echo "   - Container 'node-backend' Last Status: RUNNING"
echo "   - Exit Code: (empty or 0)"
echo ""

echo "=" 
echo "STEP 3: Container Logs"
echo "="
echo "1. In Task Details, scroll down to Logs"
echo "2. Click the log stream"
echo "3. YOU SHOULD SEE:"
echo "   'App listening at http://0.0.0.0:3000'"
echo ""
echo "   IF YOU SEE ERRORS:"
echo "   - The app crashed"
echo "   - Fix the error and push to GitHub"
echo "   - GitHub Actions will rebuild and redeploy"
echo ""

echo "=" 
echo "STEP 4: Network Configuration"
echo "="
echo "1. In Task Details, go to Network section"
echo "2. Look for: 'Attachments' → 'networkInterfaceId'"
echo "3. You should see an ENI like: eni-xxxxxxxxx"
echo "4. Record it - we'll need it next"
echo ""

echo "=" 
echo "STEP 5: Security Group Rules"
echo "="
echo "1. Go to EC2 → Security Groups"
echo "2. Find the security group attached to your task"
echo "3. Click it → Inbound rules"
echo "4. YOU SHOULD SEE:"
echo "   - Type: Custom TCP (or All Traffic)"
echo "   - Port: 3000 (or All)"
echo "   - Source: 0.0.0.0/0"
echo ""
echo "   IF PORT 3000 IS NOT THERE:"
echo "   - Click 'Edit inbound rules'"
echo "   - Add rule:"
echo "     * Type: Custom TCP"
echo "     * Port: 3000"
echo "     * Source: 0.0.0.0/0"
echo "   - Save and wait 30 seconds"
echo ""

echo "=" 
echo "STEP 6: Check ENI Details"
echo "="
echo "1. Go to EC2 → Network Interfaces"
echo "2. Search for the ENI ID from Step 4"
echo "3. Under 'Details' tab:"
echo "   - Public IPv4 Address: Should match your IP"
echo "   - Elastic IP: (might be empty)"
echo "   - Public IP Auto-assign: (check if enabled)"
echo ""

echo "=" 
echo "STEP 7: Outbound Rules"
echo "="
echo "1. Go back to the Security Group"
echo "2. Click 'Outbound rules' tab"
echo "3. YOU SHOULD SEE:"
echo "   - Type: All traffic"
echo "   - Destination: 0.0.0.0/0"
echo ""
echo "   If this is NOT there:"
echo "   - Add it by clicking 'Edit outbound rules'"
echo ""

echo ""
echo "=================================="
echo "❓ Common Issues & Fixes"
echo "=================================="
echo ""
echo "Issue: Task shows STOPPED"
echo "Fix: Check logs for errors, fix code, push to GitHub"
echo ""
echo "Issue: Port 3000 not in security group"
echo "Fix: Add inbound rule for port 3000"
echo ""
echo "Issue: No Public IP assigned"
echo "Fix: Re-create service with assignPublicIp=ENABLED"
echo ""
echo "Issue: Still can't connect"
echo "Fix: Verify subnet has Internet Gateway attached"
echo ""

echo ""
echo "=================================="
echo "✅ Once Everything is Configured"
echo "=================================="
echo ""
echo "Test with:"
echo "curl http://<public-ip>:3000/"
echo ""
echo "You should see: Hello World!"
